server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymDB?createDatabaseIfNotExist=true
    username: root
    password: dgnk1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

