server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymDB?createDatabaseIfNotExist=true
    # url: jdbc:mysql://gymappdbserver.mysql.database.azure.com:3306/gymDB?createDatabaseIfNotExist=true
    username: root
    password: root@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

